### ISSUE TITLE
Error on start-up

### ISSUE THREAD

**Issue by iondarie** [e-mcgee/paradox_platform#26]
Hello,

Every time i try to start homebridge i get this error...

Can this plugin be made to work with a serial connection?

Thank you,

`[7/5/2018, 9:14:58 PM] [paradox] Initializing Paradox platform...
[7/5/2018, 9:14:58 PM] [paradox] Platform initialisation
[7/5/2018, 9:14:58 PM] [paradox] MQTT URL - 127.0.0.1
[7/5/2018, 9:14:58 PM] [paradox] Publish Options
[7/5/2018, 9:14:58 PM] [paradox] Client ID
[7/5/2018, 9:14:58 PM] [paradox] Connecting to MQTT Broker

/usr/lib/node_modules/homebridge-paradox-securitysystem/node_modules/mqtt/lib/connect/index.js:64
      throw new Error('Missing protocol')
            ^
Error: Missing protocol
    at Object.connect (/usr/lib/node_modules/homebridge-paradox-securitysystem/node_modules/mqtt/lib/connect/index.js:64:13)
    at new paradoxPlatform (/usr/lib/node_modules/homebridge-paradox-securitysystem/index.js:1193:27)
    at Server._loadPlatforms (/usr/lib/node_modules/homebridge/lib/server.js:325:32)
    at Server.run (/usr/lib/node_modules/homebridge/lib/server.js:85:36)
    at module.exports (/usr/lib/node_modules/homebridge/lib/cli.js:43:10)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:236:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:560:3)`

**Comment by iondarie** [comment]
Is there any chance the script can be modified to connect to the alarm by serial connection?

I am willing to donate/pay for this. I have the IP150 with the new firmware and unfortunately no script works on it except serial connections

**Comment by e-mcgee** [comment]
I suspect your MQTT broker is running older version.  See: https://www.npmjs.com/package/mqtt for details on how to change your options to support v3.1 instead of 3.1.1

**Comment by gcherem** [comment]
Hello there @e-mcgee , I am having the same problem. That doc says: 

If you are connecting to a broker that supports only MQTT 3.1 (not 3.1.1 compliant), you should pass these additional options:

```
{
  protocolId: 'MQIsdp',
  protocolVersion: 3
}
```

But where do I do that? Thanks
