### ISSUE TITLE
Few issues

### ISSUE THREAD

**Issue by deon-wentzel** [e-mcgee/paradox_platform#3]
I am trying to install this plug-in but have picked up the following error

====================
[5/6/2017, 10:24:39 AM] ERROR LOADING PLUGIN homebridge-paradox-securitysystem:
[5/6/2017, 10:24:39 AM] Error: Cannot find module 'system-sleep'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-paradox-securitysystem/index.js:3:13)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
[5/6/2017, 10:24:39 AM] ====================

If I copy the latest index.js I get the following error

====================
[5/6/2017, 10:39:46 AM] ERROR LOADING PLUGIN homebridge-paradox-securitysystem:
[5/6/2017, 10:39:46 AM] /usr/local/lib/node_modules/homebridge-paradox-securitysystem/index.js:91
    ]
    ^
SyntaxError: Unexpected token ]
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Plugin.load (/usr/local/lib/node_modules/homebridge/lib/plugin.js:65:22)
[5/6/2017, 10:39:46 AM] ====================

**Comment by e-mcgee** [comment]
Apologies.  I believe you used one of my interim versions.  I am busy trying to get a checksum verification of data received back from Paradox going, so there are going to be some interim versions.  The Syntax error was fixed earlier today.

I also failed to include the "dependencies" section in my Package.json which resulted in you not getting the "system-sleep" module.  I fixed now in version 0.20.  Just tested now and it seems stable so please try. I did not have this issue as I had the module installed and did not get the error.  Should be all good now.

**Comment by deon-wentzel** [comment]
Thanks, installed this morning and saw no errors.
