### ISSUE TITLE
Can connect, but reads badly nor being able to control

### ISSUE THREAD

**Issue by iFac3** [e-mcgee/paradox_platform#33]
Hi e-mcgee,

First of all thank you for your work, it's a very nice thing to adding HomeKit support for this ageing alarm platform!

My issue is similar to others what have already been closed, however not the same. I've read out all the similar issues before I decided to raise an issue.

The connection to the IP module seems to be established, however if I set something in the Home app, nothing changes on the alarm control panel and vice versa. 

Details:

<img width="528" alt="Képernyőfotó 2020-03-26 - 23 46 10" src="https://user-images.githubusercontent.com/51527573/77703836-05333c00-6fbc-11ea-8661-64214834336c.png">

One Partition, only PIRs and contact sensors, 28 zones. Default PC password.

After switching on Connect in Home app, this happens:

[ConnectON.txt](https://github.com/e-mcgee/paradox_platform/files/4390438/ConnectON.txt)

Completely out of synch with the reality.

Hope you can help me.

**Comment by e-mcgee** [comment]
Hi, can you  share your config file please?

**Comment by iFac3** [comment]
Hi,

Of course:

        {
            "platform": "Paradox",
            "ip": “***.***.***.***",
            "port": 10000,
            "password": “********",
            "mqtt": false,
            "mqtturl": "x.x.x.x",
            "qos": 0,
            "retain": false,
            "mqttusername": "user",
            "mqttpassword": "password",
            "logindelay": 3800,
            "polldelay": 5000,
            "waitafterlogin": 600,
            "delaybetweencmds": 250,
            "logoutdelay": 500,
            "logindelayafterreconnect": 1000,
            "accessories": [
                {
                    "name": "Alarm_Partition_1",
                    "config": {
                        "type": "Alarm",
                        "partition": 0,
                        "topic": "Paradox/partition1/"
                    }
                },
                {
                    "name": "inactive",
                    "config": {
                        "type": "Alarm",
                        "partition": 1,
                        "topic": "Paradox/partition2/"
                    }
                },
                {
                    "name": "Connected",
                    "config": {
                        "type": "Connected"
                    }
                },
                {
                    "name": "Entrance",
                    "config": {
                        "type": "Motion Sensor",
                        "zone": 3,
                        "topic": "Paradox/motionsensor1/",
                        "debounceDelay": 0
                    }
                }
            ]
        }

Rgds,

**Comment by e-mcgee** [comment]
Hi,

you only have on sensor (zone 3) defined.  You need to define every zone (ll 28) separately as you did for zone 3.  It seems as if you get the status of the alarm and zone defined OK.  If you define all the zones you should get all of them.

**Comment by iFac3** [comment]
Hi,

I added more zones, however I realised that I have less zones, numbering is tricky:

<img width="469" alt="Képernyőfotó 2020-04-10 - 7 13 55" src="https://user-images.githubusercontent.com/51527573/78964577-f8096780-7afa-11ea-9197-f3063fd2fced.png">

Anyway, I added all except Siren (SZIRÉNA). Issue still the same, can connect, but reads badly nor being able to control.

Here is a part of the log: 
[Log20200410.xlsx](https://github.com/e-mcgee/paradox_platform/files/4460052/Log20200410.xlsx)

This log created while I connected to the IP module, then set alarm status in Home app multiple times, then opened 4 windows, but nothing happened...  Paradox had not changed alarm status, contact sensors had not reported open status in home app.

**Comment by e-mcgee** [comment]
I see your log file does not show the alarm status correctly.  Can you please send me the logs while homebridge is starting?

**Comment by iFac3** [comment]
Here you are: 

[BootUp.xlsx](https://github.com/e-mcgee/paradox_platform/files/4484019/BootUp.xlsx)

(I've changed IP in the mean time form 172.17.17.251 to 250. Config json was modified accordingly)

**Comment by iFac3** [comment]
Hi e-mcgee,

Have you had time to check the bootup.xlsx?

Rgds,
G.

**Comment by danieljakab** [comment]
@iFac3 Hi G. As far as I see you are writing from Hungary as well :)  I have a quick question: which mqtt plugin are you using with homebridge and this plugin? 

@e-mcgee Hi, upon homebridge startup it stucks in a loop with a "missing protocol". Not quite sure what the issue might be here, probably missing mqtt plugin? If so which one would you suggest to use with your plugin? 

Thank you!

Looping log: 
[1/1/2021, 8:11:57 PM] Got SIGTERM, shutting down Homebridge...
[1/1/2021, 8:12:02 PM] [HB Supervisor] Homebridge Process Ended. Code: 143, Signal: null
[1/1/2021, 8:12:07 PM] [HB Supervisor] Restarting Homebridge...
[1/1/2021, 8:12:07 PM] [HB Supervisor] Starting Homebridge with extra flags: -I
[1/1/2021, 8:12:07 PM] [HB Supervisor] Started Homebridge v1.1.7 with PID: 70899
[1/1/2021, 8:12:07 PM] Loaded config.json with 1 accessories and 2 platforms.
[1/1/2021, 8:12:07 PM] ---
[1/1/2021, 8:12:08 PM] Loaded plugin: homebridge-config-ui-x@4.36.0
[1/1/2021, 8:12:08 PM] Registering platform 'homebridge-config-ui-x.config'
[1/1/2021, 8:12:08 PM] ---
[1/1/2021, 8:12:08 PM] Loaded plugin: homebridge-gree-ac@1.0.2
[1/1/2021, 8:12:08 PM] Registering accessory 'homebridge-gree-ac.GreeAC'
[1/1/2021, 8:12:08 PM] ---
[1/1/2021, 8:12:08 PM] Loaded plugin: homebridge-paradox-securitysystem@0.0.380
[1/1/2021, 8:12:08 PM] Registering platform 'homebridge-paradox-securitysystem.Paradox'
[1/1/2021, 8:12:08 PM] ---
[1/1/2021, 8:12:08 PM] Loading 2 platforms...
[1/1/2021, 8:12:08 PM] [Config] Initializing config platform...
[1/1/2021, 8:12:08 PM] [Config] Running in Service Mode
[1/1/2021, 8:12:08 PM] [Paradox] Initializing Paradox platform...
[1/1/2021, 8:12:08 PM] [Paradox] Platform initialisation
[1/1/2021, 8:12:08 PM] [Paradox] MQTT URL - x.x.x.x
[1/1/2021, 8:12:08 PM] [Paradox] Publish Options
[1/1/2021, 8:12:08 PM] [Paradox] Client ID
[1/1/2021, 8:12:08 PM] [Paradox] Connecting to MQTT Broker
[1/1/2021, 8:12:08 PM] Error: Missing protocol
at Object.connect (/usr/local/lib/node_modules/homebridge-paradox-securitysystem/node_modules/mqtt/lib/connect/index.js:71:13)
at new paradoxPlatform (/usr/local/lib/node_modules/homebridge-paradox-securitysystem/index.js:1185:27)
at /usr/local/lib/node_modules/homebridge/src/server.ts:397:40
at Array.forEach (<anonymous>)
at Server.loadPlatforms (/usr/local/lib/node_modules/homebridge/src/server.ts:374:27)
at Server.start (/usr/local/lib/node_modules/homebridge/src/server.ts:153:29)
at cli (/usr/local/lib/node_modules/homebridge/src/cli.ts:80:10)
at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
at Module._compile (internal/modules/cjs/loader.js:1063:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)

**Comment by iFac3** [comment]
@danieljakab Hi J.

I have not used MQTT, as you can see in config above ( "mqtt": false,) since it isn't mandatory for this plugin.

**Comment by danieljakab** [comment]
@iFac3 Hi G.
Thank for your reply! The ( "mqtt": false,) setting was the key to success! Currently I onle have issues with the log in. It gives back an login error:

[1/5/2021, 8:27:39 PM] [Paradox] Checksum not OK
[1/5/2021, 8:27:39 PM] [Paradox] Error logging in
[1/5/2021, 8:27:44 PM] [Paradox] Mute : [false]
[1/5/2021, 8:27:44 PM] [Paradox] Logging in
[1/5/2021, 8:27:44 PM] [Paradox] Getting Status - Connected to alarm!
[1/5/2021, 8:27:44 PM] [Paradox] Message received
[1/5/2021, 8:27:44 PM] [Paradox] message length = 
[1/5/2021, 8:27:44 PM] [Paradox] 43

Did you use your user pincode as password, or is there any more "tricks" to it?

Köszi!

D

**Comment by danieljakab** [comment]
@iFac3 BTW. as I can see e-mcgee did not respond to your BootUP.xlsx question. Did you manage to make the system work, as you wish to work at all?

**Comment by iFac3** [comment]
Nope... 😔

Üdv,

G.

**Comment by iFac3** [comment]
Nope, you need the password what you use at the Paradox web portal.

Üdv,

G.

**Comment by danieljakab** [comment]
@iFac3 
OOO... That is sad:S

@e-mcgee Hi, we are stuck a bit with the plugin. Can you please have a look at the question of @iFac3 about the bootup.xlsx?

**Comment by danieljakab** [comment]
@iFac3 
Szia! Did you manage to make it work? I started to use Home Assistant, and it is working flawless for the past 1,5 months. Jist checking back... maybe worth having a look. The PAI is developed for Home Assistant, has great documentation and community. Let me know if you need more info. Cheers

**Comment by iFac3** [comment]
Szia Dániel!

Nope, It's done by an other solution.

Üdv,

G.

**Comment by ElphaX** [comment]
Would love some assistance from fellow users, what do i have to configure with MQTT?

**Comment by lukasnevosad** [comment]
I am stuck with the exactly same problem, anyone found a solution? The plugin is able to log in, but all configured zones are always "Off" and I am not able to control any PGM nor arm/disarm the alarm itself.

I am also using "mqtt": false
